/* Architecture Notes — BMC widget 用 名言プール (rev 2026-07-20b: Pages ビルド再発火のための無害な版数コメント)
   形式 [source, en, ja]。source が "" のものは出典表示なし (現場のことわざ)。
   追加ルール: ソース込みで ja <= 48 字 / en <= 100 字 (吹き出し 3 行以内)。
   利用箇所: 各ページ末尾のインライン script (document.write で BMC タグを書き込む)。 */
window.BMC_QUOTES = [
  ["Linus Torvalds", "Talk is cheap. Show me the code.", "議論は安い。コードを見せろ。"],
  ["Donald E. Knuth", "Premature optimization is the root of all evil.", "早すぎる最適化は諸悪の根源である。"],
  ["John Johnson", "First, solve the problem. Then, write the code.", "まず問題を解決し、それからコードを書け。"],
  ["Edsger W. Dijkstra", "Simplicity is prerequisite for reliability.", "シンプルさは信頼性の前提である。"],
  ["Ron Jeffries", "Code never lies, comments sometimes do.", "コードは嘘をつかない。コメントは時に嘘をつく。"],
  ["Fred Brooks", "Adding manpower to a late software project makes it later.", "遅れたプロジェクトに人員を追加すると、さらに遅れる。"],
  ["Eric S. Raymond", "Given enough eyeballs, all bugs are shallow.", "十分な数の目があれば、すべてのバグは浅い。"],
  ["Kent Beck", "Make it work, make it right, make it fast.", "まず動かし、次に正しくし、最後に速くする。"],
  ["Erich Gamma", "Design for change.", "変更に強い設計をする。"],
  ["Burt Rutan", "Testing leads to failure, and failure leads to understanding.", "テストは失敗を生み、失敗は理解を生む。"],
  ["Jeff Atwood", "The best code is no code at all.", "最高のコードは、書かないコードだ。"],
  ["Donald E. Knuth", "We should forget about small efficiencies, say about 97% of the time.", "小さな効率化は、ほとんどの場合忘れるべきだ。"],
  ["Kelly Johnson", "Keep It Simple, Stupid.", "シンプルに保て。バカ。"],
  ["The Pragmatic Programmer", "Don't Repeat Yourself.", "同じことを繰り返さない。"],
  ["Extreme Programming", "You Aren't Gonna Need It.", "今必要でないものは作らない。"],
  ["Edsger W. Dijkstra", "Separation of Concerns.", "関心事を分離する。"],
  ["Ruby on Rails", "Convention over Configuration.", "設定より規約。"],
  ["Erlang", "Fail Fast.", "早く失敗する。"],
  ["Design Patterns", "Favor Composition over Inheritance.", "継承よりコンポジションを優先する。"],
  ["Design Patterns", "Program to an Interface, not an Implementation.", "実装ではなくインターフェースに依存する。"],
  ["Agile Manifesto", "Simplicity—the art of maximizing the amount of work not done.", "シンプルさとは、やらない仕事を最大化すること。"],
  ["ITIL / PMBOK", "Focus on value.", "価値に焦点を当てる。"],
  ["ITIL", "Start where you are.", "現状から始める。"],
  ["ITIL", "Progress iteratively with feedback.", "フィードバックを得ながら反復的に進める。"],
  ["ITIL", "Collaborate and promote visibility.", "協力し、可視性を高める。"],
  ["ITIL", "Think and work holistically.", "全体を考え、全体として取り組む。"],
  ["ITIL", "Keep it simple and practical.", "シンプルで実践的に保つ。"],
  ["ITIL", "Optimize and automate.", "最適化し、自動化する。"],
  ["PMBOK", "Be a diligent, respectful, and caring steward.", "誠実で、敬意を持ち、責任ある管理者である。"],
  ["PMBOK", "Create a collaborative project team environment.", "協力的なプロジェクトチーム環境を構築する。"],
  ["PMBOK", "Effectively engage with stakeholders.", "ステークホルダーと効果的に関わる。"],
  ["PMBOK", "Recognize, evaluate, and respond to system interactions.", "システムの相互作用を認識・評価・対応する。"],
  ["PMBOK", "Demonstrate leadership behaviors.", "リーダーシップを発揮する。"],
  ["PMBOK", "Tailor based on context.", "状況に応じてテーラリングする。"],
  ["PMBOK", "Build quality into processes and deliverables.", "プロセスと成果物に品質を組み込む。"],
  ["PMBOK", "Navigate complexity.", "複雑性に対応する。"],
  ["PMBOK", "Optimize risk responses.", "リスク対応を最適化する。"],
  ["PMBOK", "Embrace adaptability and resilience.", "適応性とレジリエンスを受け入れる。"],
  ["PMBOK", "Enable change to achieve the envisioned future state.", "望ましい未来を実現するために変化を促進する。"],
  ["Software Engineering", "It works on my machine.", "私の環境では動きます。"],
  ["Programming Joke", "It works. Don't touch it.", "動いている。触るな。"],
  ["Programming Joke", "It's not a bug. It's a feature.", "バグではない。仕様だ。"],
  ["Programming Culture", "Ship it.", "出荷しよう。"],
  ["DevOps", "It only fails in production.", "本番でだけ壊れる。"],
  ["Programming Joke", "Nothing is more permanent than a temporary solution.", "仮実装ほど永遠なものはない。"],
  ["Programming Culture", "TODO: Fix this later.", "あとで直す。"],
  ["Programming Joke", "One more quick fix...", "あと一つだけ直そう。"],
  ["Programming Joke", "But it worked yesterday.", "昨日までは動いてた。"],
  ["Programming Joke", "Missing semicolon.", "セミコロンがない。"],
  ["IT Support", "Have you tried turning it off and on again?", "一度再起動しましたか?"],
  ["DevOps", "Never deploy on Friday.", "金曜日にデプロイするな。"],
  ["DBA Humor", "Friends don't let friends update production.", "友達なら本番DBを更新させない。"],
  ["Programming Joke", "The code is the documentation.", "コードがドキュメントだ。"],
  ["Programming Joke", "Now you have two problems.", "正規表現を使ったら問題が二つになった。"],
  ["Developer Humor", "Coffee. Because debugging is hard.", "デバッグにはコーヒー。"],
  ["Programming Joke", "It's not stupid if it works.", "動くならバカな方法じゃない。"],
  ["", "Writing code is expressing intent.", "コードを書くことは、やりたいことを言語化すること。"],
  ["", "PnP. Plug and Pray.", "PnP。繋げたら祈れ。"],
  ["Daisuke Aramaki", "Understanding is largely based on one's own desires.", "理解なんてものは概ね願望に基づくものだ。"],
  ["", "A bug that doesn't work is just a bug. A bug that works is a feature.", "動かないバグはただのバグだ。動くバグは仕様だ。"],
  ["", "If it survives for a year, it's no longer a bug—it's a feature.", "1年動けば、バグは仕様に変わる。"],
  ["", "The PoC became production.", "PoCがそのまま本番。"],
  ["", "The sample code became production code.", "サンプルコードがそのまま運用。"],
  ["", "That's staging.", "それステージ環境です。"],
  ["", "It rarely happens... very often.", "稀によくある。"],
  ["", "Risk management is deciding what to do when it happens.", "リスク管理は、起きた時にどうするかを決めること。"],
  ["", "System behavior and business interpretation are not the same.", "システム機能とビジネス解釈は違う。"],
  ["", "Don't ask the system for business requirements.", "システムにビジネス要件を聞かないで。"],
  ["", "Agile does not mean changing requirements anytime.", "仕様変更をいつでもしていいのがアジャイルではない。"],
  ["", "We'll think about it when it happens.", "発生してから考える。"],
  ["", "Business requirements are not system requirements.", "ビジネス要件とシステム要件は違う。"],
  ["", "Implementation is not the specification.", "実装は仕様ではない。"],
  ["", "A screen is not a requirement.", "画面は要件ではない。"],
  ["", "Data is truth. Screens are interpretations.", "データが真実であり、画面はその解釈である。"],
  ["Network Humor", "Layer 8 problem.", "第8層の問題 (ユーザー)。"],
  ["Network Humor", "Who edited the hosts file?", "誰だ hosts を書いたのは。"],
  ["Linux", "chmod 2777", "chmod 2777"],
  ["Linux", "sudo su", "sudo su"],
  ["Linux", "kill -9", "kill -9"]
];
